### ISSUE TITLE
Make exercise cards the same height

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/react#443]
The variation exercise cards in the detail view can be of different height, it would be better if their height would be equal for all

![Bildschirmfoto 2022-09-22 um 15 41 11](https://user-images.githubusercontent.com/2280729/191763130-af0fd2b6-5c2f-4b87-9ea1-13b8d70aa8c4.png)

**Comment by Makhosetive7** [comment]
@rolandgeider i'm a beginner can i work on this issue?

**Comment by rolandgeider** [comment]
Hi @Makhosetive7 ! Sure, the issue is yours.

You can use these settings for your .env.development (the DB is reset every day)
```
REACT_APP_API_SERVER=https://wger-master.rge.uber.space
REACT_APP_API_KEY="31e2ea0322c07b9df583a9b6d1e794f7139e78d4"
```

**Comment by tlatawiec** [comment]
Would you prefer the height to fit the full content of the card? This would mean that all cards are the same height as the "tallest". Or have all card contents be cutoff at a certain maximum height?

**Comment by rolandgeider** [comment]
hi @tlatawiec

I would say fit to the tallest one, the name is already cutoff after a maximum length

**Comment by rolandgeider** [comment]
wait, it seems this was already fixed in the meantime 😄 

closing here
