### ISSUE TITLE
Implement calendar dashboard widget

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/react#445]
Implement the calendar widget for the dashboard. This should mark in a calendar the days for which there are entries (body weight, nutrition or workout logs, etc.)

Flutter version:

![image](https://user-images.githubusercontent.com/2280729/192105543-5cf98a4e-ebc0-4bb8-83fb-29204310241f.png)

Depends on #17, #12, #13

**Comment by codemaniac-sahil** [comment]
Hello @rolandgeider, I would like to work on this issue. Would you please assign this issue to me.

**Comment by rolandgeider** [comment]
Hi! Go ahead. We still haven't implemented any of the models we would need for this, but you can still start. We would need a calendar that marks the days where "entries" for that day exist. An entry is currently simply an object with a title (like "Meassurement" in the screenshot) and what happended, like a new weight entry or such.

**Comment by tejask1730** [comment]
@rolandgeider CAN YOU PLZZ ASSIGN ME THIS TASK

**Comment by codemaniac-sahil** [comment]
@rolandgeider you can assign this issue to @tejask1730

**Comment by rolandgeider** [comment]
it's yours @tejask1730

**Comment by tejask1730** [comment]
Okk i will do it

**Comment by rolandgeider** [comment]
@TomasTerpitko all yours

**Comment by TomasTerpitko** [comment]
Thanks. already on it

**Comment by rolandgeider** [comment]
merged, thanks 💪🏻
