### ISSUE TITLE
Add helper to manage the URLs

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/react#455]
We could add a little helper that generates the URLs used since they need to be kept in sync with the django ones. That would also allow us to write something like

```tsx
<CardActionArea href={makeUrl(UrlEnum.ExerciseDetail, i18n.language, exerciseBase.id)} />
```
instead of

```tsx
<CardActionArea href={`/${i18n.language}/exercise/${exerciseBase.id}/view-base/${exercise.nameSlug}`} />
```

Current list of URLs (all with a language prefix, but that should be made optional later on):

- `/exercise/<baseId>/view-base/<nameSlug>`
- `/exercise/overview`
- `/exercise/contribute`
- `/weight/overview`

**Comment by shivamchourasia4** [comment]
I would like to work on this. Can you assign this to me, please?

**Comment by rolandgeider** [comment]
Hi @shivamchourasia4 ! It's yours

**Comment by rolandgeider** [comment]
BTW, there is already a `makeUrl` function, we should call this one something else. Something like makeNavigationUrl perhaps?

**Comment by rolandgeider** [comment]
Note that `i18n.language` might return something like "de-DE", which we can't use on the django side so we will need to cut this to just "de" in this case
