### ISSUE TITLE
Add generic header component

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/react#456]
Since we will be using more and more components for the application, we should have a generic header component that we can reuse. What exactly we will need besides a title (options? buttons? etc?) needs to be discussed

**Comment by codemaniac-sahil** [comment]
Hello @rolandgeider, I would like to work on this issue.

**Comment by rolandgeider** [comment]
BTW, you can use these settings for your .env.development (the DB is reset every day)

```
REACT_APP_API_SERVER=https://wger-master.rge.uber.space
REACT_APP_API_KEY="31e2ea0322c07b9df583a9b6d1e794f7139e78d
```

**Comment by codemaniac-sahil** [comment]
Okay @rolandgeider

**Comment by codemaniac-sahil** [comment]
Would you please tell me which components you want me to add in header component.

**Comment by rolandgeider** [comment]
In any case

- a title
- additional components unter the title (e.g. for the exercises the category and so on)
- a list of options/menus at the right (where the exercise has the edit/delete ones)
- space at the top left for something like breadcrumbs

Having the grey area span the whole width would be great as well

**Comment by codemaniac-sahil** [comment]
Okay @rolandgeider, I got this and I am working this.

**Comment by codemaniac-sahil** [comment]
@rolandgeider would you please arrange a discord meet with me. Actually I having a certain doubts.

**Comment by rolandgeider** [comment]
@codemaniac-sahil sorry I had missed the last message. Sure, we can meet over discord
