### ISSUE TITLE
Fix matched / leaf bug

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/react#51]
Small bug, when opening `/` this warning is logged to the console

```
index.tsx:25 Matched leaf route at location "/" does not have an element. This means it will render an <Outlet /> with a null value by default resulting in an "empty" page.
```

**Comment by SakaRicky** [comment]
- Ok I see this. It demands and index or landing page. I intentionally made weight overview NOT the landing page because it's just a feature.

**Comment by rolandgeider** [comment]
We need a dashboard as the landing page anyway, I can add one. If I understood it correctly we need one route where the path is `/`, right?

**Comment by SakaRicky** [comment]
Yeah that’s exactly it
