### ISSUE TITLE
Sort weight entries after adding/editing

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/react#59]
When adding or editing a weight entry, we need to sort the whole list so that they are ordered by date

**Comment by SakaRicky** [comment]
- Like the new or updated one shouldn't directly be added to the top of the table?
- I think we sorted already before displaying, so we sort again after updating the state right?

**Comment by rolandgeider** [comment]
You can add an entry for a date in the past for example. Also, we need the entries themselves sorted, otherwise the chart will be broken (and we won't need to sort the table entries again)
