### ISSUE TITLE
Wait till we get an answer from the server

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/react#67]
Right now, we immediately add/update/remove weight entries without waiting for the answer from the server. Specially when editing or adding objects server side validation responses are currently ignored.

We should wait till a successfull answer from the server before updating the state

**Comment by SakaRicky** [comment]
- So since the server don't send back the added, edited or deleted weight, we just use the status code to proceed with?

**Comment by rolandgeider** [comment]
It does send back the added weight (I'm not sure about the edited one). It might also send back some messages when the validation fails (try e.g. to add a weight entry for a date that already has one)

**Comment by SakaRicky** [comment]
This issue is still to be done right?
