### ISSUE TITLE
Positioning problems with floating action button

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/react#99]
The floating action button can partially cover the weight entries table and it also makes problems when the components are used in the django application. As a workaround, the button can be removed so that we can ship the react improvements, but sooner or later we will need to fix this.

**Comment by rolandgeider** [comment]
![152361447-d637bfc0-dc18-43db-9f25-148317136766](https://user-images.githubusercontent.com/2280729/152363383-d07960d9-2fc6-4020-8240-48d80b3bc2f4.png)

**Comment by SakaRicky** [comment]
OK we would add this floating add button later right?

**Comment by rolandgeider** [comment]
Yeah

**Comment by SakaRicky** [comment]
OK. Why did you choose to just remove?
Because of some challenges?

**Comment by rolandgeider** [comment]
It was something I didn't want to do now 😄

**Comment by rolandgeider** [comment]
this would be resolved by #447
